apiVersion: v1
kind: Service
metadata:
  name: week5-config-flask-service
  namespace: week5-config
spec:
  selector:
    app: week5-config-flask
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30082

