pipeline {
  agent any

  environment {
    IMAGE = "devsecops-demo:latest"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build Docker Image') {
      steps {
        sh '''
        docker build -t $IMAGE ../Day4-Jenkins-Docker-ECR/app
        '''
      }
    }

    stage('Load Image into kind Cluster') {
      steps {
        sh '''
        kind load docker-image $IMAGE --name devops-kind
        '''
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        sh '''
        kubectl apply -f k8s/
        '''
      }
    }

    stage('Verify Deployment') {
      steps {
        sh '''
        kubectl get pods
        kubectl get svc
        '''
      }
    }

  }
}
