[web]
3.95.235.101 ansible_user=ubuntu ansible_ssh_private_key_file=../Day3-Ansible-EC2/keys/devops-keypair

[app]
52.72.41.195 ansible_user=ubuntu ansible_ssh_private_key_file=../Day3-Ansible-EC2/keys/devops-keypair
