apiVersion: apps/v1
kind: Deployment
metadata:
  name: week5-flask-deploy
  namespace: week5-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: week5-flask
  template:
    metadata:
      labels:
        app: week5-flask
    spec:
      imagePullSecrets:
        - name: ecr-pull-secret
      containers:
        - name: week5-flask-container
          image: 953816747017.dkr.ecr.us-east-1.amazonaws.com/week5-flask-app:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000

