apiVersion: v1
kind: Service
metadata:
  name: week5-flask-service
  namespace: week5-app
spec:
  selector:
    app: week5-flask
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30081

